pub(crate) use anyhow::{Context, Result};
pub(crate) use clap::Parser;
pub(crate) use reqwest::Url;
pub(crate) use serde::de::DeserializeOwned;
pub(crate) use serde::{Deserialize, Serialize};
pub(crate) use std::collections::HashMap;
pub(crate) use std::fs::OpenOptions;
pub(crate) use std::io::{self, IsTerminal, Write};
pub(crate) use std::path::{Path, PathBuf};
pub(crate) use std::process::Command;
pub(crate) use std::sync::{Mutex, OnceLock};
pub(crate) use std::time::{Duration, SystemTime, UNIX_EPOCH};

mod app;
mod app_bootstrap;
mod app_chat;
mod app_chat_core;
mod app_chat_handlers;
mod app_chat_helpers;
mod app_chat_trace;
mod decomposition;  // Task 023: Hierarchical decomposition
mod defaults;
mod defaults_core;
mod defaults_evidence;
mod defaults_router;
mod evaluation;
mod evaluation_response;
mod evaluation_routing;
mod evaluation_workflow;
mod execution;
mod execution_steps;
mod execution_steps_compat;
mod execution_steps_edit;
mod execution_steps_shell;
mod intel;
mod metrics;
mod models_api;
mod optimization;
mod optimization_eval;
mod optimization_tune;
mod orchestration;
mod orchestration_core;
mod orchestration_helpers;
mod orchestration_loop;
mod orchestration_loop_helpers;
mod orchestration_loop_reviewers;
mod orchestration_planning;
mod orchestration_retry;
mod paths;
mod profile_sets;
mod program;
mod program_policy;
mod program_steps;
mod program_utils;
mod reflection;
mod refinement;
mod routing;
mod routing_calc;
mod routing_infer;
mod routing_parse;
mod scenarios;
mod session;
mod session_error;
mod session_hierarchy;
mod session_paths;
mod session_seq;
mod session_write;
mod snapshot;
mod storage;
mod text_utils;
mod thinking_content;
mod tool_discovery;
mod tune;
mod tune_runtime;
mod tune_scenario;
mod tune_setup;
mod tune_summary;
mod tuning_support;
mod types;
mod types_api;
mod types_core;
mod types_hierarchy;
mod ui;
mod ui_chat;
mod ui_colors;
mod ui_state;
mod ui_trace;
mod verification;
mod workspace;

pub(crate) use defaults::*;
pub(crate) use evaluation::*;
pub(crate) use execution::*;
pub(crate) use intel::*;
pub(crate) use metrics::*;
pub(crate) use models_api::*;
pub(crate) use optimization::*;
pub(crate) use decomposition::*;  // Task 023
pub(crate) use orchestration::*;
pub(crate) use paths::*;
pub(crate) use profile_sets::*;
pub(crate) use program::*;
pub(crate) use reflection::*;
pub(crate) use refinement::*;
pub(crate) use routing::*;
pub(crate) use scenarios::*;
pub(crate) use session::*;
pub(crate) use snapshot::*;
pub(crate) use storage::*;
pub(crate) use text_utils::*;
pub(crate) use thinking_content::*;
pub(crate) use tune::*;
pub(crate) use tuning_support::*;
pub(crate) use types::*;
pub(crate) use ui::*;
pub(crate) use verification::*;
pub(crate) use workspace::*;

#[tokio::main]
async fn main() -> Result<()> {
    app::run().await
}
