//! @efficiency-role: storage-state
//!
//! Task persistence for session-scoped task items and _elma-tasks/ files.
//!
//! Two storage targets:
//! 1. `sessions/<id>/runtime_tasks/tasks.json` — recoverable per-session task list
//! 2. `_elma-tasks/NNN_auto_Task_Name_uid.md` — auto-generated or user-initiated task files

use anyhow::{Context, Result};
use std::path::{Path, PathBuf};
use serde::{Deserialize, Serialize};

/// Single task item derived from an Instruction node in the work graph.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub(crate) struct PersistedTask {
    pub id: u32,
    pub instruction_id: String,
    pub approach_id: String,
    pub description: String,
    pub status: TaskItemStatus,
    pub step_type: String,
    pub step_result: Option<String>,
    pub created_at: u64,
    pub completed_at: Option<u64>,
}

#[derive(Debug, Clone, Copy, PartialEq, Serialize, Deserialize)]
pub(crate) enum TaskItemStatus {
    #[serde(rename = "pending")]
    Pending,
    #[serde(rename = "in_progress")]
    InProgress,
    #[serde(rename = "completed")]
    Completed,
    #[serde(rename = "failed")]
    Failed,
    #[serde(rename = "blocked")]
    Blocked,
}

impl TaskItemStatus {
    pub fn as_str(&self) -> &'static str {
        match self {
            TaskItemStatus::Pending => "pending",
            TaskItemStatus::InProgress => "in_progress",
            TaskItemStatus::Completed => "completed",
            TaskItemStatus::Failed => "failed",
            TaskItemStatus::Blocked => "blocked",
        }
    }
}

/// Container for all persisted tasks in a session.
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub(crate) struct PersistedTaskList {
    pub tasks: Vec<PersistedTask>,
    pub next_id: u32,
}

impl PersistedTaskList {
    pub fn new() -> Self {
        Self {
            tasks: Vec::new(),
            next_id: 1,
        }
    }

    pub fn add_task(&mut self, task: PersistedTask) {
        self.tasks.push(task);
        self.next_id += 1;
    }

    pub fn update_status(&mut self, id: u32, status: TaskItemStatus) {
        if let Some(task) = self.tasks.iter_mut().find(|t| t.id == id) {
            task.status = status;
            if status == TaskItemStatus::Completed || status == TaskItemStatus::Failed {
                task.completed_at = Some(now_unix_s());
            }
        }
    }
}

// ── Session Task Persistence ──────────────────────────────────────────

pub(crate) fn session_task_file(session_root: &Path) -> PathBuf {
    session_root.join("runtime_tasks").join("tasks.json")
}

pub(crate) fn load_session_tasks(session_root: &Path) -> Option<PersistedTaskList> {
    let path = session_task_file(session_root);
    let json = std::fs::read_to_string(path).ok()?;
    serde_json::from_str(&json).ok()
}

pub(crate) fn save_session_tasks(session_root: &Path, list: &PersistedTaskList) -> Result<()> {
    let dir = session_root.join("runtime_tasks");
    std::fs::create_dir_all(&dir).context("create runtime_tasks dir")?;
    let path = session_task_file(session_root);
    let json = serde_json::to_string_pretty(list).context("serialize task list")?;
    std::fs::write(&path, json).context("write tasks.json")?;
    Ok(())
}

// ── _elma-tasks/ File Generation ──────────────────────────────────────

pub(crate) enum TaskSource {
    /// Auto-generated by workflow (Instruction node resolution)
    Workflow,
    /// Initiated by direct user request
    User,
}

/// Generate the next task filename from the _elma-tasks/ directory.
pub(crate) fn next_task_filename(elma_tasks_dir: &Path) -> (u32, String) {
    let existing = existing_task_numbers(elma_tasks_dir);
    let next = existing.iter().max().map(|n| n + 1).unwrap_or(1);
    (next, format!("{:03}", next))
}

fn existing_task_numbers(dir: &Path) -> Vec<u32> {
    let mut nums = Vec::new();
    if let Ok(entries) = std::fs::read_dir(dir) {
        for entry in entries.flatten() {
            let name = entry.file_name();
            let name = name.to_string_lossy();
            if let Some(num) = name
                .split('_')
                .next()
                .and_then(|s| s.parse::<u32>().ok())
            {
                nums.push(num);
            }
        }
    }
    nums
}

pub(crate) fn ensure_elma_tasks_dir(workspace: &Path) -> Result<PathBuf> {
    let dir = workspace.join("_elma-tasks");
    std::fs::create_dir_all(&dir).context("create _elma-tasks dir")?;
    Ok(dir)
}

pub(crate) fn write_task_file(
    workspace: &Path,
    number: u32,
    title: &str,
    description: &str,
    session_id: &str,
    approach_id: &str,
    graph_node_id: &str,
    source: TaskSource,
) -> Result<PathBuf> {
    let dir = ensure_elma_tasks_dir(workspace)?;
    let slug = slugify(title);

    let source_label = match source {
        TaskSource::Workflow => "auto",
        TaskSource::User => "user",
    };

    let filename = format!("{:03}_{}_{}_{}.md", number, source_label, slug, graph_node_id);
    let path = dir.join(&filename);

    let now = chrono::Utc::now().to_rfc3339();
    let content = format!(
        "# Task {:03}: {}\n\
         - **Status:** active\n\
         - **Source:** {}\n\
         - **Session:** {}\n\
         - **Approach:** {}\n\
         - **Graph node:** {} (Instruction)\n\
         - **Created:** {}\n\
         \n\
         {}\n",
        number, title, source_label, session_id, approach_id, graph_node_id, now, description
    );

    std::fs::write(&path, content).with_context(|| format!("write {:?}", path))?;
    Ok(path)
}

fn slugify(title: &str) -> String {
    title
        .to_lowercase()
        .chars()
        .map(|c| if c.is_alphanumeric() { c } else { '_' })
        .collect::<String>()
        .split('_')
        .filter(|s| !s.is_empty())
        .collect::<Vec<_>>()
        .join("_")
}

fn now_unix_s() -> u64 {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap_or_default()
        .as_secs()
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::tempdir;

    #[test]
    fn test_persisted_task_list_add_and_update() {
        let mut list = PersistedTaskList::new();
        let task = PersistedTask {
            id: 1,
            instruction_id: "instr_001".to_string(),
            approach_id: "a_123".to_string(),
            description: "Read Cargo.toml".to_string(),
            status: TaskItemStatus::Pending,
            step_type: "read".to_string(),
            step_result: None,
            created_at: 1000,
            completed_at: None,
        };
        list.add_task(task);
        assert_eq!(list.tasks.len(), 1);
        assert_eq!(list.next_id, 2);

        list.update_status(1, TaskItemStatus::Completed);
        assert_eq!(list.tasks[0].status, TaskItemStatus::Completed);
        assert!(list.tasks[0].completed_at.is_some());
    }

    #[test]
    fn test_session_task_roundtrip() {
        let tmp = tempdir().unwrap();
        let mut list = PersistedTaskList::new();
        list.add_task(PersistedTask {
            id: 1,
            instruction_id: "instr_001".to_string(),
            approach_id: "a_123".to_string(),
            description: "Read Cargo.toml".to_string(),
            status: TaskItemStatus::Completed,
            step_type: "read".to_string(),
            step_result: Some("success".to_string()),
            created_at: 1000,
            completed_at: Some(1005),
        });

        save_session_tasks(tmp.path(), &list).unwrap();
        let loaded = load_session_tasks(tmp.path()).unwrap();
        assert_eq!(loaded.tasks.len(), 1);
        assert_eq!(loaded.tasks[0].description, "Read Cargo.toml");
    }

    #[test]
    fn test_task_file_generation() {
        let tmp = tempdir().unwrap();
        let workspace = tmp.path();

        let path = write_task_file(
            workspace,
            1,
            "Read Cargo.toml",
            "Read the Cargo.toml to inspect dependencies",
            "sess_abc",
            "a_123",
            "instr_001",
            TaskSource::Workflow,
        )
        .unwrap();

        assert!(path.exists());
        let content = std::fs::read_to_string(&path).unwrap();
        assert!(content.contains("Read Cargo.toml"));
        assert!(content.contains("auto"));
        assert!(content.contains("sess_abc"));

        let fname = path.file_name().unwrap().to_string_lossy();
        assert!(fname.starts_with("001_auto_"));
        assert!(fname.ends_with("_instr_001.md"));
    }

    #[test]
    fn test_next_task_number() {
        let tmp = tempdir().unwrap();
        let dir = tmp.path().join("_elma-tasks");
        std::fs::create_dir_all(&dir).unwrap();
        std::fs::write(dir.join("001_existing.md"), "").unwrap();
        std::fs::write(dir.join("002_another.md"), "").unwrap();

        let (next, formatted) = next_task_filename(&dir);
        assert_eq!(next, 3);
        assert_eq!(formatted, "003");
    }

    #[test]
    fn test_next_task_number_empty_dir() {
        let tmp = tempdir().unwrap();
        let dir = tmp.path().join("_elma-tasks");
        std::fs::create_dir_all(&dir).unwrap();

        let (next, formatted) = next_task_filename(&dir);
        assert_eq!(next, 1);
        assert_eq!(formatted, "001");
    }

    #[test]
    fn test_slugify() {
        assert_eq!(slugify("Read Cargo.toml"), "read_cargo_toml");
        assert_eq!(slugify("Fix Bug #42"), "fix_bug_42");
        assert_eq!(slugify("simple_task"), "simple_task");
    }

    #[test]
    fn test_status_as_str() {
        assert_eq!(TaskItemStatus::Pending.as_str(), "pending");
        assert_eq!(TaskItemStatus::Completed.as_str(), "completed");
        assert_eq!(TaskItemStatus::Failed.as_str(), "failed");
    }
}
